### ISSUE TITLE
`devspace dev` only deploys last manifest

### ISSUE THREAD

**Issue by rparsonsbb** [devspace-cloud/devspace#1028]
**What happened?**  
When deploying with a devspace.yaml like below:
```
deployments:
- name: cbb-sf-api
  kubectl:
    manifests:
    - manifests/**
dev: {}
```
only the last manifest alphabetically by filename is deployed.
i.e. in folder `manifests`:
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         3/23/2020   9:39 PM            466 dp-cbb-sf.yaml
-a----         3/23/2020   9:36 PM            499 dp-mysql.yaml
-a----         3/23/2020   9:36 PM            527 dp-phpmyadmin.yaml
-a----         3/23/2020   9:38 PM            137 svc-mysql.yaml
-a----         3/23/2020   9:37 PM            667 svc-phpmyadmin.yaml
```
running `devspace dev`:
```
Successfully built cd21515c3877
Successfully tagged cbb-sf-image:n4NzaPF
[info]   Skip image push for cbb-sf-image
[done] √ Done processing image 'cbb-sf-image'
service/phpmyadmin unchanged
[done] √ Successfully deployed cbb-sf-api with kubectl

#########################################################
[info]   DevSpace UI available at: http://localhost:8090
#########################################################
```
**What did you expect to happen instead?**  
devspace dev would run all manifests in the directory.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
create a directory with multiple manifest files or even a single file with multiple k8s objects and `deploy dev`.  With multiple files the last file deploys, with multiple manifests in single file the last manifest deploys.

**Local Environment:**  
- DevSpace Version: devspace version 4.8.0
- Operating System: windows
- Deployment method: kubectl apply
- Kubernetes: Docker Desktop

**Kubernetes Cluster:**  
- Cloud Provider: google | aws | azure | DevSpace Cloud | DevSpace Cloud Enterprise | other
- Kubernetes Version: [use `kubectl version`]

**Anything else we need to know?**  
I'm very new to devspace and this could totally be me but it seems odd and possibly an issue.

When you break it out individually like
```
- name: cbb-sf-api
  kubectl:
    manifests:
    - manifests/dp-cbb-sf.yaml
- name: mysql
  kubectl:
    manifests:
    - manifests/dp-mysql.yaml
    - manifests/svc-mysql.yaml
- name: phpmysqladmin
  kubectl:
    manifests:
    - manifests/dp-phpmyadmin.yaml
    - manifests/svc-phpmyadmin.yaml
```
it seems to work, but why be able to wildcard gather manifests if it only executes one?

/kind bug

**Comment by FabianKramm** [comment]
@rparsonsbb thanks for reporting this issue! Actually we recommend to specify the manifests just like this:
```
deployments:
- name: cbb-sf-api
  kubectl:
    manifests:
    - manifests
dev: {}
```
The wildcard was the old syntax, which should not be used anymore. Does this work for you?
