### ISSUE TITLE
howto setup custom tag attribute inside devspace.yml ?

### ISSUE THREAD

**Issue by Slach** [devspace-cloud/devspace#1087]
**What happened?**  
install and run minikube inside Ubuntu 18.04 vagrant / virtualbox VM
install `devspace` inside virtualbox VM
i successfully run `cd /vagrant; devspace init` 
and create following /vagrant/devspace.yaml
```
version: v1beta9
images:
  metrics-exporter:
    image: docker.io/mycompany/metrics-exporter:devspace
    dockerfile: ./dockerfile/metrics-exporter/Dockerfile
    context: ./
    preferSyncOverRebuild: true
    injectRestartHelper: true
    build:
      docker:
        skipPush: true
deployments:
- name: metrics-exporter
  kubectl:
    kustomize: true
    manifests:
      - deploy/devspace/kustomize.yaml
dev:
  ports:
  - imageName: metrics-exporter
    forward:
    - port: 8888
  open:
  - url: http://localhost:8888
  sync:
  - imageName: metrics-exporter
    excludePaths:
    - .git/
    uploadExcludePaths:
    - vendor
    - .vagrant
    - .idea
    - '*.log'
    - devspace.yaml
    onUpload:
      restartContainer: true
profiles:
- name: production
  patches:
  - op: remove
    path: images.app.injectRestartHelper
```

run `devspace dev`

**What did you expect to happen instead?**  
I expect successful docker build with image tagged as `mycompany/metrics-exporter:devspace`

Instead of I got the following error:
```
[fatal]  Error building image: Error building image docker.io/mycompany/clickhouse-operator:devspace:JOEPye5: Info: Building image 'docker.io/mycompany/clickhouse-operator:devspace:JOEPye5' with engine 'docker'
 Error during image build: Error response from daemon: invalid reference format
```

I can't use `image` with format without tag, cause I use deployment.yaml where I try to replace ImagePullPolicy and image via `kustomize`
 
**How can we reproduce the bug?** (as minimally and precisely as possible)  
just try set image inside devspace.yml with format `registry/repo/image:tag`

**Local Environment:**  
- DevSpace Version: [use `devspace --version`]
- Operating System: Linux 
Deployment method:  kubectl -k apply

**Kubernetes Cluster:**  
- Cloud Provider: minikube
- Kubernetes Version: 1.17.3

this bug related to
https://github.com/devspace-cloud/devspace/issues/559
but I try to use a different format for Image

/kind bug

**Comment by FabianKramm** [comment]
@Slach thanks for reporting this issue! There is an option called `images.*.tags` that you can use to specify your custom tag `devspace`. Your config would look like:
```yaml
version: v1beta9
images:
  metrics-exporter:
    image: docker.io/mycompany/metrics-exporter
    tags: ["devspace"]
    dockerfile: ./dockerfile/metrics-exporter/Dockerfile
    context: ./
    preferSyncOverRebuild: true
    injectRestartHelper: true
    build:
      docker:
        skipPush: true
deployments:
- name: metrics-exporter
  kubectl:
    kustomize: true
    manifests:
      - deploy/devspace/kustomize.yaml
dev:
  ports:
  - imageName: metrics-exporter
    forward:
    - port: 8888
  open:
  - url: http://localhost:8888
  sync:
  - imageName: metrics-exporter
    excludePaths:
    - .git/
    uploadExcludePaths:
    - vendor
    - .vagrant
    - .idea
    - '*.log'
    - devspace.yaml
    onUpload:
      restartContainer: true
profiles:
- name: production
  patches:
  - op: remove
    path: images.app.injectRestartHelper
```
