### ISSUE TITLE
devspace dev not logging sync events to the console

### ISSUE THREAD

**Issue by FloChehab** [devspace-cloud/devspace#1111]
First of all, thank you for the awesome tool! Since you have introduced me about it @LukasGentele, I have been using it daily :)
At first, I was using only the `sync` command and I got used to the logging it does in the console.
For a couple of days, I've started using the `dev` command but I can't manage to get the similar logs in the console.

**What happened?**  
Running `devspace dev` or `devspace dev --verbose-sync` doesn't show any sync related logs in the console (but they are in the `.devspace` folder).

**What did you expect to happen instead?**  
All sync related events to be logged to the console when running `devspace dev [--verbose-sync]`.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
I doesn't seem to be linked to the config (everything is pretty closed to default).
Here is the config I am using for `devspace sync`:

```yaml
version: v1beta6

dev:
  sync:
    - excludePaths:
      - node_modules/
      - logs/
      - '.venv/'
      - '*.pyc'
      - '.git'
      - 'core.python.*'
```
I can work on a real simple example if needed. 

**Local Environment:**  
- DevSpace Version: v4.12.5
- Operating System: linux
- Deployment method: kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: google
- Kubernetes Version: v1.18.2

**Anything else we need to know?**  
I've tried to look at the code related to dev / sync but I am not that familiar with go.

/kind bug
