### ISSUE TITLE
`devspace update config` substitutes some variable references with their values

### ISSUE THREAD

**Issue by gbates101** [devspace-cloud/devspace#1120]
**What happened?**  
In some of our `devspace.yaml` files we heavily use vars to template project configs. When I run `devspace update config`, it takes some of the ${VAR} references in the `deployments[].helm.values` section of the config and substitutes with the actual value, which we don't want since we version these `devspace.yaml` files in git for many to use. Seems to only impact lists (see bottom of post for more detail).

**What did you expect to happen instead?**  
Leave all ${VAR} references in the `devspace.yaml` alone, so the dev's helm deployment can be (re)configured without modifying the `devspace.yaml` file directly.

**How can we reproduce the bug?** (as minimally and precisely as possible) 
```yaml
version: v1beta9
vars:
- name: SUBDOMAIN
  question: "Enter the subdomain where your site will be hosted."
  source: input
deployments:
- name: my-app
  helm:
    chart:
      name: ./charts/my-app
    values:
      ingress:
        enabled: true
        hostnames:
        - ${SUBDOMAIN}.example.com
```
1. Dump the above into a `devspace.yaml` file. Doesn't need to reference an actual chart or anything.
2. Run `devspace update config` and enter a value like 'my-site'

The operation will substitute the ${SUBDOMAIN} with the actual value of 'my-site'.

**Local Environment:**  
- DevSpace Version: 4.12.5
- Operating System: windows (wsl)
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: google
- Kubernetes Version:
    - Client Version: v1.15.5
    - Server Version: v1.16.8-gke.15

**Anything else we need to know?**  

If the above values section would be:
```yaml
...
    values:
      ingress:
        enabled: true
        hostname: ${SUBDOMAIN}.example.com
```
instead (converting from list to str), the `devspace update config` doesn't perform the substitution. I think this bug only impacts lists.

/kind bug
