### ISSUE TITLE
Bug: Helm Deployment boolean not replacing from valuesFile

### ISSUE THREAD

**Issue by Babynigel** [devspace-cloud/devspace#1143]
I have setup a helm deployment and I am using the valuesFile functionality to reference a file with my desired values.
But when using the valuesFile I am unable to run 'devspace deploy/dev' commands when I have a boolean variable that needs replacing. I have also tried setting the value as string.

eg:

cloneOnStart: true     or     cloneOnStart: "true".

Interesting enough is that this works if I hardcode the value string version "true/false" in my template file. 
Also interesting is that the devspace render command generates the correct manifest for this as well.
But it cannot be deployed this way??

**Comment by FabianKramm** [comment]
@Babynigel thanks for reporting this issue! So I tested it on my local computer with a boolean value within a values file, but it works for me, so I think I'll need some additional information about this issue. What is the error message you receive from `devspace dev/deploy`? Furthermore could you provide me a small yaml example with which I can reproduce this issue?

**Comment by Babynigel** [comment]
@FabianKramm  below is an example of this occurrence. The below error is experienced with this configuration.
This error is caused by the cloneOnStart value in the values.yaml file. however if I hardcode the boolean string in the template this works fine.

```
[fatal]  Error deploying: Error deploying config-server: Unable to deploy helm chart: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found t, error found in #10 byte of ...|,"value":true},{"nam|..., bigger context ...|_CLOUD_CONFIG_SERVER_GIT_CLONE-ON-START","value":true},{"name":"SPRING_CLOUD_CONFIG_SERVER_GIT_URI",|...
Run `devspace purge -d config-server` and `devspace deploy` to recreate the chart

```



devspace.yaml file:

```
version: v1beta8

deployments:
  - name: config-server
    helm:
      chart:
        name: ./helm
      valuesFiles:
        - ./helm/values.yaml

```
values.yaml file :

```
name: config-server
image: voyant/config-server
version: 2.2.2.RELEASE
port: 80
cloneOnStart: "true"
uri: https://gitlab.com/config-repo.git

```
Helm template deployment file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{ $.Values.name }}
      app.kubernetes.io/component: {{ $.Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: {{ $.Values.name }}
        app.kubernetes.io/component: {{ $.Values.name }}
    spec:
      containers:
        - name: {{$.Values.name }}
          image: {{ $.Values.image }}:{{  $.Values.version }}
          ports:
            - containerPort: {{ $.Values.port }}
          env:
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE-ON-START
              value: {{ $.Values.cloneOnStart }}
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: {{ $.Values.uri }}
```
