### ISSUE TITLE
DevSpace CLI stuck at project initialization step

### ISSUE THREAD

**Issue by tingkai-zhang** [devspace-cloud/devspace#1148]
**What happened?**  
I followed the getting started tutorial to initialize the quick-start python project.
When I do `devspace init` and choose the option `Use the Dockerfile in ./Dockerfile`, the CLI stuck at this step.

![image](https://user-images.githubusercontent.com/20318562/89338929-5094df80-d66b-11ea-835d-6d1497119a7c.png)

**What did you expect to happen instead?**  

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Install CLI using Linux bash. 
Follow the official instruction to initialize the quick-start python project. 

**Local Environment:**  
- DevSpace Version: devspace version 4.14.0
- Operating System: ubuntu 20.04 LTS
- Deployment method: -

**Kubernetes Cluster:**  
- Cloud Provider: -
- Kubernetes Version: Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6" }

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@tingkai-zhang thanks for opening this issue! This is either caused by docker or kubectl hanging, can you check if either of the following commands is hanging for you:
```
docker images
```
or 
```
kubectl get ns
```

**Comment by tingkai-zhang** [comment]
> @tingkai-zhang thanks for opening this issue! This is either caused by docker or kubectl hanging, can you check if one of the following commands is hanging for you:
> 
> ```
> docker images
> ```
> 
> or
> 
> ```
> kubectl get ns
> ```

Hi @FabianKramm ! Thanks for replying.
None of these two commands is hanging. They all correctly returned the k8s namespaces and docker images.
What else information can I provide for you to investigate this issue?

**Comment by FabianKramm** [comment]
@tingkai-zhang thanks for the additional information! Mhh thats odd, usually it is one of the two commands. Do you have minikube installed by any chance and the current kubernetes context points to that? Could be that the minikube docker daemon is hanging.  

What kind of kubernetes cluster are you using?

**Comment by tingkai-zhang** [comment]
> @tingkai-zhang thanks for the additional information! Mhh thats odd, usually it is one of the two commands. Do you have minikube installed by any chance and the current kubernetes context points to that? Could be that the minikube docker daemon is hanging.
> 
> What kind of kubernetes cluster are you using?

@FabianKramm  I don't have minikube installed. 

I ran a 3-node K8s cluster on bare metal machines. The current context points to that cluster.

**Comment by FabianKramm** [comment]
@tingkai-zhang okay, could you try with v5.0.0 and see if that makes any difference, there were some changes to the init process

**Comment by tingkai-zhang** [comment]
> @tingkai-zhang okay, could you try with v5.0.0 and see if that makes any difference, there were some changes to the init process

Just upgraded devspace and tried it out. Still stuck at the `use Dockerfile ...` step.
Is there a log file generated during init process that I can provide you?

**Comment by tingkai-zhang** [comment]
ah sorry, I should've put WSL2 in the system info. The WSL2 distro is Ubuntu 20.04 LTS.
So I think the problem has something to do with WSL2. 
Did anyone experience this before and could provide some thoughts on this?

**Comment by LukasGentele** [comment]
@tingkai-zhang I just tried to reproduce this with our golang quickstart project, WSL2 Ubuntu 20.04 on Windows 10 64 bit and it runs through for me. It's a clean WSL2 Ubuntu instance. Hard to tell what's going wrong.

While we try to find the cause of this issue, you can still use devspace by just manually creating a devspace.yaml because that is essentially everything that `devspace init` does in the end. Here is an example for the quickstart-golang project with a couple of annotations for you:

```yaml
version: v1beta9
images:
  app:
    image: DOCKER_HUB_USERNAME/quickstartgolang               # or use gcr.io, ecr or any other private registry you want to push to
    preferSyncOverRebuild: true
    injectRestartHelper: true
    appendDockerfileInstructions:
    - USER root
    build:
      docker:
        options:
          target: build
deployments:
- name: quickstart-golang # feel free to rename this
  helm:
    componentChart: true
    values:
      containers:
      - image: DOCKER_HUB_USERNAME/quickstartgolang          # use the same image here as above
      service:
        ports:
        - port: 8080                                                                          # use the port of your application here
dev:
  ports:
  - imageName: app
    forward:
    - port: 8080                                                                              # use the port of your application here
  open:
  - url: http://localhost:8080                                                         # use the port of your application here
  sync:
  - imageName: app
    excludePaths:
    - .git/
    uploadExcludePaths:
    - Dockerfile
    - devspace.yaml
    onUpload:
      restartContainer: true
profiles:
- name: production
  patches:
  - op: remove
    path: images.app.injectRestartHelper
  - op: remove
    path: images.app.appendDockerfileInstructions
  - op: remove
    path: images.app.build.docker.options.target
```
That should at least get you started without having to wait until we find a way to reproduce this issue. I hope that helps.
