### ISSUE TITLE
Add DEVSPACE_PROFILE to predefined variables

### ISSUE THREAD

**Issue by QwertyQaz414** [devspace-cloud/devspace#1160]
**Is your feature request related to a problem?**  
No

**Which solution do you suggest?**  
Add a predefined variable called `DEVSPACE_PROFILE` which contains the current profile being used.

e.g. launching devspace with `devspace deploy -p my_profile` (or `devspace use profile my_profile`) will set `DEVSPACE_PROFILE` to `my_profile` inside `devspace.yaml`

**Which alternative solutions exist?**  
This worked for me but it's a bit redundant.

```yaml
vars:
- name: DEVSPACE_PROFILE
  source: none
  default: ""

profiles:
- name: development
  patches:
    - op: replace
      path: vars.name=DEVSPACE_PROFILE.default
      value: development

deployments:
- name: my_chart
  helm:
    chart:
      name: ./charts/my_chart
    values:
      profile: ${DEVSPACE_PROFILE}
```

however, with `DEVSPACE_PROFILE` as a predefined variable this would become:

```yaml
profiles:
- name: development

deployments:
- name: my_chart
  helm:
    chart:
      name: ./charts/my_chart
    values:
      profile: ${DEVSPACE_PROFILE}
```

**Additional context**  

I have a bunch of ad-hoc charts where the deployment logic is handled by the helm templating engine instead of variable files for better consistency between profiles.

/kind feature
