### ISSUE TITLE
Way to create image pull secret even if you don't build an image

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#1172]
**Is your feature request related to a problem?**  

I have a pod (from prefect) that wants to dynamically create other pods. To do so, it needs to pull images from my private docker registry. I don't need to actually build an image when I create deployment using
devspace, but I was hoping to find some trick to create the image pull secret so I wouldn't have to create a script to build and push it myself (doable but annoying).

**Which solution do you suggest?**  

I was hoping the following hack would work:
```
images:
  dummy:
    image: <my registry>/dummy
    createPullSecret: true
    build:
      disabled: true
```
Unfortunately, it doesn't.

**Which alternative solutions exist?**  

Create image oneself without devspace.

**Additional context**  

Besides the hack above (which, if it were to work, could be documented), another "bespoke" option could be added.

/kind feature
