### ISSUE TITLE
Using onUpload post-sync commands does not work as expected

### ISSUE THREAD

**Issue by zWaR** [devspace-cloud/devspace#1176]
**What happened?**  
Using any of the post-sync commands yields an error on `devspace dev`. The error is similar to the below (exact error depends on which configuration option I try to use (execRemote | onFileChange | onDirChange | onBatch):

```
[fatal]  convert config: Error loading config: yaml: unmarshal errors:
line 25: field onFileChange not found in type v1beta8.SyncOnUpload
```

**What did you expect to happen instead?**  
I expected that the configured command would run on the remote end on the on file changed event.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Add `onFileChange` configuration to your devspace.yaml file and run `devspace dev`.

**Local Environment:**  
- DevSpace Version: devspace version 5.0.3
- Operating System: mac
- Deployment method: kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: aws 
- Kubernetes Version: 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T19:10:58Z", GoVersion:"go1.15.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  
Here's the sync snippet from my `devspace.yaml` file:

```yaml
dev:
  sync:
    - containerName: myContainer
      containerPath: /my-path
      labelSelector:
        app: myApp
      localSubPath: ./src/mySrc
    - imageName: myImage
      onUpload:
        onFileChange:
          command: s6-svc
          args:
          - -t
          - /path/to/config
```

/kind bug
