### ISSUE TITLE
passing user credentials to private helm repo

### ISSUE THREAD

**Issue by blairham** [devspace-cloud/devspace#1182]
**Is your feature request related to a problem?**  
Yes, you can not pull helm charts from a private helm repo that requires user credentials

**Which solution do you suggest?**  
add the following to the devspace.yaml
```
      chart:
        name: hello-world
        repo: http://my-private-repo.com
        username: joe-user
        password: my-password
```

**Which alternative solutions exist?**  
allowing anonymous access

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
@blairham thanks for opening this issue! Devspace should actually already support this, did you encounter any errors while using this?

**Comment by blairham** [comment]
@FabianKramm I couldn't find any documentation on how to pass in the credentials. I tried to use http://<username>:<password>@<repo> and still got an error:

```
[fatal]  Error deploying: Error deploying xxxxxxxx: Unable to deploy helm chart: failed to download "https://xxxxx-1.0.0.tgz" (hint: running `helm repo update` may help)
```

**Comment by FabianKramm** [comment]
@blairham yes you are right, its apparently missing in the docs, however the following should actually work:

```
chart:
  name: hello-world
  repo: http://my-private-repo.com
  username: joe-user
  password: my-password
```
