### ISSUE TITLE
Images always rebuild due to use of DEVSPACE_RANDOM in image tag

### ISSUE THREAD

**Issue by khaled** [devspace-cloud/devspace#1188]
**What happened?**  

I've noticed that my images always rebuild when running `devspace dev`, despite having `preferSyncOverRebuild` set to true.

It appears that using `DEVSPACE_RANDOM` as part of my image tag leads to this.

I'm using kaniko to build, so there's a significant unnecessary wait time every time I run `devspace dev`, even though kaniko is caching the layers.  In other words, a kaniko pod has to spin up, the context files are synced to the pod, layer hashes are calculated and checked against the cache for each step, etc.

**What did you expect to happen instead?**  
The image does not rebuild every time.  Instead, the prior image tag is re-used, and a sync happens on startup.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Use `DEVSPACE_RANDOM` as the tag in an image.

**Local Environment:**  
- DevSpace Version:  5.03
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: 1.15

**Anything else we need to know?**  

This appears to have to do with the calculation of `imageConfigHash` in `helper.go`.  The image config contains the tag, which is a new random value every time you run `devspace dev`.  Ideally there could be a special case in how `imageConfigHash` is calculated when DEVSPACE_RANDOM is used as part of the tag.  For example, the hash could be calculated prior to replacing the DEVSPACE_RANDOM variable with a random value.

A snippet from the related Slack thread:
<img width="578" alt="Screen Shot 2020-10-03 at 10 15 07 AM" src="https://user-images.githubusercontent.com/11412/94993774-528ef800-0561-11eb-9c27-69534421ff39.png">

/kind bug

**Comment by FabianKramm** [comment]
@khaled thanks for reporting this issue! This is actually a tricky problem since variable resolution happens very early in the command and I'll have to think about it for a good solution. As a workaround you could use `devspace dev -x` which would just skip building the image if you know that a rebuild is not necessary.

**Comment by FabianKramm** [comment]
@khaled we introduced `appendRandomTags` to prevent this issue in v5.4.1

**Comment by khaled** [comment]
@FabianKramm would you mind explaining? It's not clear how adding appending a random suffix to tags would help...

**Comment by FabianKramm** [comment]
@khaled sure, I guess `appendRandomTags` is not a perfect solution, however it prevents the issue of:
```yaml
tags:
- some-prefix-${DEVSPACE_RANDOM}
```

The reason why this issue existed in the first place is because devspace took a hash of the image config and compared it to the hash of the image config before, which leads to a rebuild every time since ${DEVSPACE_RANDOM} takes a different value each time the config is loaded. 

With `appendRandomTags`, the image config looks the same for each build, hence why caching works in this case. If a rebuild happens `appendRandomTags` will also add a random value as suffix to the tags and mimic the behavior of ${DEVSPACE_RANDOM} which essentially is a workaround for the problem you have described.

Since `appendRandomTags` is not as flexible as ${DEVSPACE_RANDOM} it is not a perfect solution for now and we will probably improve it in some way in the future to make it more flexible. I hope this clears it up a little bit.

**Comment by khaled** [comment]
@FabianKramm thanks for the explanation! Sadly, this does not seem to help my use case.  My config needs to know what the image tag actually is, so that I can use it as a chart value.  

The chart deployment defines `image` similar to the following, and unfortunately I don't have control over the way the chart is designed:

```
...
image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
```

And `replaceImageTags` doesn't appear to be an option because it's not actually replacing the tag in there AFAICT.  It's only appending the tag if there isn't already one.

If I leave `image.tag` empty I end up with:
```yaml
image: whatever:
```

...which is invalid yaml.

**Comment by FabianKramm** [comment]
@khaled that will both be fixed in the next version, which we will release very soon.

**Comment by FabianKramm** [comment]
@khaled this should work with v5.6.1 now! You can use something like:
```yaml
images:         
  image1:                       
    image: registry.url/repo/image
    tags:                     
    - dev-###
deployments:
- name: backend
  helm:
    chart:
      name: chart-name
      repo: https://my-charts.company.tld/
    values:
      # If registry.url/repo/image was found under images as well, will be 
      # rewritten to registry.url/repo/image:generated_tag
      imageWithTag: registry.url/repo/image
      # If registry.url/repo/image was found under images as well, will be
      # rewritten to registry.url/repo/image
      imageWithoutTag: image(registry.url/repo/image)
      # If registry.url/repo/image was found under images as well, will be
      # rewritten to generated_tag
      onlyTag: tag(registry.url/repo/image)
```

In this case DevSpace caching will work as expected

**Comment by khaled** [comment]
Awesome @FabianKramm! I'll give it a try!

**Comment by khaled** [comment]
@FabianKramm I followed your example and ran into trouble.  I'm using version 5.7.1.

My helm chart:
```yaml
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
```

devspace.yaml:

```yaml
vars:
  - name: REGISTRY_BASE_URL
    default: blaa.amazonaws.com
    source: env
images:
  backend:
    image: '${REGISTRY_BASE_URL}/tc/backend'
    tags:
      - tc-#####
    ...
deployments:
  - name: backend
    helm:
      chart:
        name: backend/chart
      replaceImageTags: true
      values:
        image:
          repository: '${REGISTRY_BASE_URL}/tc/backend'
          tag: 'tag(${REGISTRY_BASE_URL}/tc/backend)'
```

The deployed yaml:
```yaml
   image: blaa.amazonaws.com/tc/backend:tc-gwq0H:tc-gwq0H
```

So the tag appears twice.  Note that I had to set `replaceImageTags` to `true` for `tag()` to get replaced at all.
