### ISSUE TITLE
devspace is replacing container environment variables in unpleasant way

### ISSUE THREAD

**Issue by timo-klarshift** [devspace-cloud/devspace#1209]
**What happened?**  
I am trying to access environment variables in `container_2` which for no special reason consist of values which have the name of `container_1` in it. After deploying and checking the env variables in `container_2` i see the content of the variables being suffixed with the container hash of devspace.

**What did you expect to happen instead?**  
Environment Variables are present in container as provided.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
```
version: v1beta9

images:
  app:
    image: app
    dockerfile: Dockerfile
    preferSyncOverRebuild: true
    build:
      docker:
        useBuildKit: true
        skipPush: true

deployments:
  - name: app
    helm:
      componentChart: true
      values:
        containers:
          - image: app
            env:
              - name: QUARKUS_DATASOURCE_JDBC_URL
                value: jdbc:mariadb://db:3306/app

        service:
          ports:
            - port: 8080

  - name: db
    helm:
      componentChart: true
      values:
        containers:
          - image: mariadb/server:10.4
            env:
              - name: MYSQL_ROOT_PASSWORD
                value: root
              - name: MYSQL_USER
                value: app
              - name: MYSQL_DATABASE
                value: app
              - name: MYSQL_PASSWORD
                value: app
        service:
          ports:
            - port: 3306
```

```bash
root@db-55bfcb6fdf-f9zwl:/# env | grep MYSQL
MYSQL_PASSWORD=app:sgHiKfN
MYSQL_DATABASE=app:sgHiKfN
MYSQL_ROOT_PASSWORD=root
MYSQL_USER=app:sgHiKfN
root@db-55bfcb6fdf-f9zwl:/# 

```

**Local Environment:**  
- DevSpace Version: 5.2.0
- Operating System: linux
- Deployment method: helm / devspace dev

**Kubernetes Cluster:**  
- Cloud Provider: k3s
- Kubernetes Version: v1.19.2

/kind bug
