### ISSUE TITLE
injectRestartHelper doesn't inject script nor change ENTRYPOINT+CMD

### ISSUE THREAD

**Issue by zonnie** [devspace-cloud/devspace#1221]
**What happened?**  
I've set the `injectRestartHelper` to `true` in order to use the `restartContainer: true` and syncing files doesn't trigger any restart inside the container

**What did you expect to happen instead?**  
nothing, the code is synced (it seems from the `devspace` cli output) but the restart is not triggered

**How can we reproduce the bug?** (as minimally and precisely as possible)  
I'm using this `devspace.yaml`:
```
version: v1beta9
vars:
- name: PROJECT_ID
  source: all
- name: DIST_TAG
  source: all
images: 
  test-image:
    image: gcr.io/${PROJECT_ID}/test-image
    preferSyncOverRebuild: true
    injectRestartHelper: true
    tags:
      - dev-${DEVSPACE_GIT_COMMIT}-${DEVSPACE_TIMESTAMP}
    build:
      custom:
        command: ./start_cloud_build.sh
        args:
          - "-c"
          - "cloudbuild_no_dist.yaml"
          - "-t"
          - "dev-${DEVSPACE_GIT_COMMIT}-${DEVSPACE_TIMESTAMP}"
          - "-d"
          - "${DIST_TAG}"
          - "--build-dist"
        onChange:
          - management/
deployments:
- name: app-deployment
  helm:
    chart:
      name: charts/app
    valuesFiles:
    - /tmp/prod.yaml
    values:
      app_tag: dev-${DEVSPACE_GIT_COMMIT}-${DEVSPACE_TIMESTAMP}
dev:
  sync:
  - imageName: test-image
    onUpload:
      restartContainer: true
    disableDownload: true
    containerName: test-container
    localSubPath: app
    containerPath: /var/lib/app
```
- I've got `injectRestartHelper: true`
- I've got `restartContainer: true` as well under `onUpload`

Running `devspace deploy` and later `devspace sync`.
I change some code, I see the `devspace` detecting it and copying it but nothing is being reset.

**Local Environment:**  
- DevSpace Version: `devspace version 5.2.2`
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: google 
- Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-gke.1504", GitCommit:"17061f5bd4ee34f72c9281d49f94b4f3ac31ac25", GitTreeState:"clean", BuildDate:"2020-10-19T17:00:22Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  
Nope

/kind bug
