### ISSUE TITLE
Merge / Strategic Merge not working

### ISSUE THREAD

**Issue by harryttd** [devspace-cloud/devspace#1225]
**What happened?**  

devspace.yaml
```yaml
version: v1beta9
dependencies:
  - name: foo
    source:
      path: foo

profiles:
  - name: bar
    merge:
      dependencies:
        - name: foo
          profile: yoyo

```
`devspace print`:  
```yaml
version: v1beta9
dev: {}
dependencies:
- name: foo
  source:
    path: foo
```

`devspace print -p bar`:
```yaml
version: v1beta9
dev: {}
dependencies:
- name: foo
  source:
    path: foo
```

**What did you expect to happen instead?**  
Using profile `-p bar` should update the dependency profile of `foo` to `yoyo`. The problem exists with merge and strategicMerge.

**Local Environment:**  
- DevSpace Version: [use `devspace --version`] 5.2.2
- Operating System: mac

/kind bug
