### ISSUE TITLE
devspace failing to download bitnami helm chart

### ISSUE THREAD

**Issue by bynare** [devspace-cloud/devspace#1235]
**What happened?**  
`devspace dev` fails to deploy bitnami helm chart with the following error:
```
Error deploying: Error deploying database: Unable to deploy helm chart: error during '/home/eugene/.devspace/bin/helm upgrade database bitnami/postgresql --namespace testie --values /tmp/524314694 --install --version 10.1.1 --kube-context minikube': Release "database" does not exist. Installing it now.
Error: failed to download "bitnami/postgresql" (hint: running `helm repo update` may help)
```

**What did you expect to happen instead?**  
`devspace dev` succeeds, without manually running any helm commands.

**How can we reproduce the bug?** (as minimally and precisely as possible)
* Ensure that `~/.cache/helm` and `~/.helm` is deleted.

* Ensure that  `~/.devspace/bin/helm repo list` lists no repos.

* Create a simple `devspace.yaml` containing the following deployment:
```
   deployments:
 - name: database
   helm:
     chart:
       name: bitnami/postgresql
       version: "10.1.1"
       #repo: https://charts.bitnami.com/bitnami
     values:
       postgresqlDatabase: "my_app_db"
       postgresqlUsername: "my_app_db_user"
       postgresqlPassword: ${DB_PASSWORD}
```
* run `devspace dev`

**Local Environment:**  
- DevSpace Version: 5.3.0
- Operating System: linux (ubuntu 20.04)
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: minikube
- Kubernetes Version: v1.19.4

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@bynare thanks for reporting this issue! That looks like an helm error to me, does it work if you try to deploy the chart directly via helm (hint: try using the --debug flag for information)?

**Comment by bynare** [comment]
@FabianKramm I have to manually add the bitnami repo via `~/.devspace/bin/helm repo add..` then do `~/.devspace/bin/helm repo update`. After this, `devspace dev` does its thing. I could not find any documentation (excuse me if I missed it!) referring to manually running these commands, before a helm chart would work?

**Comment by FabianKramm** [comment]
@bynare if you reference the chart via repo/chart then you have to do this beforehand. Does the error also occur if you do it like this:
```yaml
deployments:
 - name: database
   helm:
     chart:
       name: postgresql
       version: "10.1.1"
       repo: https://charts.bitnami.com/bitnami
     values:
       postgresqlDatabase: "my_app_db"
       postgresqlUsername: "my_app_db_user"
       postgresqlPassword: ${DB_PASSWORD}
```

**Comment by bynare** [comment]
@FabianKramm yeah, as you can see from my initial post, I have given that a try too (see the commented out bit - also used the `name` as you have it there).

**Comment by FabianKramm** [comment]
@bynare and if you do:
```yaml
deployments:
 - name: database
   helm:
     upgradeArgs:
     - --repository-config
     - ''
     chart:
       name: postgresql
       version: "10.1.1"
       repo: https://charts.bitnami.com/bitnami
     values:
       postgresqlDatabase: "my_app_db"
       postgresqlUsername: "my_app_db_user"
       postgresqlPassword: ${DB_PASSWORD}
```
