### ISSUE TITLE
Helm deployment not auto reloading on valuesFiles changes

### ISSUE THREAD

**Issue by harryttd** [devspace-cloud/devspace#1255]
**What happened?**  

According to the [docs](https://devspace.sh/cli/docs/configuration/development/auto-reloading#deployments):
> For helm deployments, DevSpace watches for changes in the valuesFiles or changes in the chart path of a local chart (configured as chart.name).

When i make changes to the values file, devspace does not reload!

devspace.yaml
```yaml
version: v1beta9
deployments:
  - name: hello
    helm:
      chart:
        name: ./
      valuesFiles:
        - ../../foo/bar.yaml

dev:
  autoReload:
    deployments:
      - hello
```

**What did you expect to happen instead?**  
Devspace should auto reload the deployment when a file in the `valuesFile` list is modified.

**Local Environment:**  
- DevSpace Version: devspace version 5.5.0
- Operating System:  mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Kubernetes Version: [use `kubectl version`] 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  

/kind bug
