### ISSUE TITLE
Devspace dev with adding a profile is breaking sync for completely separate image

### ISSUE THREAD

**Issue by harryttd** [devspace-cloud/devspace#1264]
**What happened?**  
```yaml
sync:
    - imageName: foo
      labelSelector:
        app: foo
      localSubPath: ./src/foo/
``` 

Running `devspace dev` without a profile syncs properly. I immediately get back:
```
[done] √ Sync started .....
[info]   Starting log streaming for containers that use images defined in devspace.yaml
```

When I run `devspace dev -p myprofile`, sync breaks and eventually logs: 
```
[fatal]  start sync: Unable to start sync: Error selecting pod: Couldn't find a pod with selector app=foo in namespace mynamespace
```
The pod most definitely exists and has the label `app=foo`.

The profile has nothing to do and is not related with the image being synced for:
```yaml
profiles:
  - name: myprofile
    strategicMerge:
      images:
        myimage:
          image: myimage
          dockerfile: ./src/myimage/Dockerfile
          context: ./src/myimage
    patches:
      - op: add
        path: dev.autoReload.images
        value: myimage
```

`devspace print` reflects the changes of the profile correctly.

**Local Environment:**  
- DevSpace Version: [use `devspace --version`] 5.5.0
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Minikube
- Kubernetes Version: [use `kubectl version`]
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
**Anything else we need to know?**  

/kind bug
