### ISSUE TITLE
image tag is added twice to deployed container

### ISSUE THREAD

**Issue by igoooor** [devspace-cloud/devspace#1271]
Here is my devspace.yaml file (important parts)
```
version: v1beta9
images:
  php:
    image: registry.local/php
    tags:
      - latest-####
    dockerfile: Dockerfile
    context: .

deployments:
- name: myproject
  helm:
    values:
      php:
        image:
          tag: tag(registry.local/php)
          repository: registry.local/php
      ...
```

And my kubernetes Deployment is using these helm values as follow:
```
...
containers:
  - name: {{ .Chart.Name }}-php
    image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}"
...
```

**What happened?**  
The deployed image was `registry.local/php:latest-4dlR:latest-4dlR`

**What did you expect to happen instead?**  
I expected the image to be `registry.local/php:latest-4dlR`
It seems like `.Values.php.image.repository` is taking the value **with the tag** when in my opinion it should not.
Did I do something wrong in the configuration?

**Local Environment:**  
- DevSpace Version: devspace version 5.6.0
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Kubernetes Version: 1.19.3

/kind bug
