### ISSUE TITLE
Using ExternalIP in devspace.yaml and devspace init

### ISSUE THREAD

**Issue by michalip** [devspace-cloud/devspace#565]
Hello, 

we can specify external IPs for services in K8s using the below yaml extract
Can we perform the same in devspace during the dialog of devspace init or at least edit the devspace.yaml for now ?

K8s yamp example for external IP
```
apiVersion: v1
kind: Service
metadata:
  name: REDUCTED
  namespace: REDUCTED
spec:
  externalIPs:
  - 10.X.X.X
  ports:
  - name: REDUCTED
```

Thank you 

**Is your feature request related to a problem?**  
Probably not but I cant find it in documentation so far

**Which solution do you suggest?**  
To follow normal K8s Yaml example

**Which alternative solutions exist?**  
manually expose the port using kubectl expose

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
@michalip thanks for opening this issue! I'm not sure if I understand the problem correctly, do you want an option in devspace.yaml in the component deployment where you can specify an external ip? If you have a working service.yaml that looks like the one you have provided you can just use the config
```
deployments:
- name: my-deployment
   kubectl:
    manifests:
    - my-folder/service.yaml
```
to let devspace deploy it.
