### ISSUE TITLE
Unable to use configMap as volume when using components

### ISSUE THREAD

**Issue by LukasGentele** [devspace-cloud/devspace#579]
**What happened?**  
Defining `volumes[].configMap.name` results in a config parsing error:
```bash
$ devspace deploy
[fatal]  Loading config: Error loading config: yaml: unmarshal errors:
  line 35: field name not found in type v1.ConfigMapVolumeSource
```

**What did you expect to happen instead?**  
DevSpace CLI should be able to parse this config correctly and define a volume for this component based on the specified configMap.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Using the following config:
```yaml
version: v1beta2
images:
  default:
    image: dscr.io/${DEVSPACE_USERNAME}/devspace
    createPullSecret: true
deployments:
- name: some-config
  kubectl:
    manifests:
    - manifests/config.yaml
- name: npm-registry
  component:
    containers:
    - image: dscr.io/${DEVSPACE_USERNAME}/devspace
      volumeMounts:
      - containerPath: /conf
        volume:
          name: config
    service:
      ports:
      - port: 8080
    volumes:
    - name: config
      configMap:
        name: some-config
```

**Anything else we need to know?**  
Might also be an issue for `secrets` as volumeSource.

/kind bug
