### ISSUE TITLE
Override ENV vars in dev

### ISSUE THREAD

**Issue by rmcclaincf** [devspace-cloud/devspace#665]
**Is your feature request related to a problem?**  
Most of our containers are 12 factor.  They can be configured entirely with environment variables.

It would be nice to not have to override the entrypoint to set ENV vars appropriate for development.  For example, setting RAILS_ENV=development turns on code reloading.

**Which solution do you suggest?**  
Allow overriding of environment variables in dev mode.

**Which alternative solutions exist?**  
Override the entrypoint to set the environment variables appropriate for dev environment.

**Additional context**  

/kind feature

**Comment by LukasGentele** [comment]
@rmcclaincf Thanks for reporting this. Overriding env vars not possible with the current config unless you redefine the entire config. However, this will be possible with DevSpace v4 which is out as a beta release since this morning. We expect to ship a stable version in a couple of days. With this version, it will be possible to add profiles to your devspace.yaml for different targets (e.g. staging prod) or for working on different services and having certain overrides for such dev cases. Overriding any value will then be possible using a patch stating the json path to the config option. In your case this could look like this:

```yaml
version: v1beta3
deployments:
  - name: component-1
    component:
      containers:
        - image: dscr.io/${DEVSPACE_USERNAME}/service-1
          env:
          - name: RAILS_ENV
            value: "development"
profiles:
- name: production
  patches:
  - op: replace
    path: deployments[0].containers[0].env[0].value
    value: "production"
```

It will be best practices to have development as a default config and use profiles for staging/prod or specific dev cases. Switching profiles will be possible using `devspace use profile PROFILE_NAME` but there will also be a `-p / --profile` flag for commands like `devspace deploy` or `devspace dev`, so you can use a different profile for a single operation rather switching the profile permanently.

Let me know if that sounds like a valid solution for this issue. Would love to hear your feedback regarding the user experience once we ship this feature.

**Comment by rmcclaincf** [comment]
This sounds good to me.  Thank you!

**Comment by LukasGentele** [comment]
Closing this as v4 is stable now.

**Comment by Slach** [comment]
hmm, look like you didn't add this enhancement in v4

line 47: field env not found in type latest.ImageConfig

should I use `images / build / custom` something like that?
```
build:
      custom:
        command: docker
        args:
        - build
        - "-f"
        - "custom/Dockerfile"
        - "--build-arg"
        - "VARNAME=value"
        - "."
```
