### ISSUE TITLE
vars don't appear to work in commands

### ISSUE THREAD

**Issue by KaelBaldwin** [devspace-cloud/devspace#698]
**What happened?**  
vars are not working in commands

**What did you expect to happen instead?**  
vars should be available for use in commands

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Using the following configuration:
```
commands:
  - name: test
    command: "echo ${USER_NAME}"
vars:
  - name: USER_NAME
    question: What is your user name?
```
run `devspace run test`

Notice you aren't prompted for the USER_NAME variable.
Notice the echo output is empty.

**Local Environment:**  
- Operating System: linux
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: bare-metal
- Kubernetes Version: v1.14.6

**Anything else we need to know?**  

/kind bug
