### ISSUE TITLE
Postgres Component: Username and Password not set

### ISSUE THREAD

**Issue by jorge0136** [devspace-cloud/devspace#722]
First thanks for building `devspace`, it's been really exciting to dig into such a rich tool. 

I am attempting to use the `postgres` database component one can add via `devspace add deployment postgres --component=postgres`

**What happened?**  
![image](https://user-images.githubusercontent.com/16239428/66071026-3cda9300-e507-11e9-859c-6e92425efe77.png)

It happily populated the following into my `.devspace.yaml`. 

```
version: v1beta3
deployments:
- name: postgres-1
  component:
    containers:
    - image: postgres:9.6
      env:
      - name: PGDATA
        value: /var/lib/postgresql/data/pgdata
      - name: POSTGRES_USER
        value: mydev
      - name: POSTGRES_PASSWORD
        value: password
      volumeMounts:
      - containerPath: /var/lib/postgresql/data/pgdata
        volume:
          name: postgres-data
          subPath: /postgres
    volumes:
    - name: postgres-data
      size: 1Gi
    service:
      name: postgres
      ports:
      - port: 5432
dev: {}
```

When I use `devspace deploy` it fires up `helm` and sends off the deployment happily, the pod comes up healthy. 

I haven't been able to successfully communicate with `postgres` from other pods at all.  I am receiving errors about my `role not existing` or my `password being incorrect.`

To simplify my troubleshooting I  port-forwarded the postgres pod directly and attempted to access the SQL instance with the CLI tool `psql`.
* `kubectl port-forward postgres-0 5432:5432` 
* `psql -h localhost -p 5432 -U mydev`
* I receive the error `psql: FATAL:  role "mydev" does not exist` 

I am able to connect to this instance of postgres with the `root` user but not my specified `mydev` user. 

One final troubleshooting step I took was to see if perhaps postgres was [creating a random password, that I needed to collect from a kubernetes secret](https://medium.com/@nicdoye/installing-postgresql-via-helm-237e026453b1). Running `kubectl get secrets --all-namespaces` didn't yield anything that looked related to postgres. 

**What did you expect to happen instead?**  
`POSTGRES_USER` and `POSTGRES_PASSWORD` to be pulled into the postgres deployment, be able to use that username and password to access the SQL instance. 

In an ideal world, I could use a Kubernetes `secret` to hold this info but I don't know how to wire that up to a devspace component. 

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Explained above but briefly steps are as follows: 

* `deployment postgres --component=postgres`
`9.6`, some non-default username, some non-default password, `1Gi`
* `devspace deploy`
* `kubectl get pods` --> Collect postgres pod name. 
* `kubectl port-forward <postgres-pod-name> 5432:5432`
* `psql -h localhost -p 5432 -U <some non-default POSTGRES_USER>`
* `psql -h localhost -p 5432 -U root`

**Local Environment:**  
- Operating System: mac
- Deployment method: helm 

**Kubernetes Cluster:**  
- Cloud Provider: docker-desktop
- Kubernetes Version: 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T13:57:45Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  

I think part of my inability to troubleshoot here is that I am not quite sure how the `devspace` components work under the hood. I can see they are `helm` charts of some sort but I don't see a way to use the built-in devspace helm client to see their state or where their charts are living. I haven't been able to issue any `devspace deploy --verbose` flags to see what the underlying commands are that are being executed. Some of my confusion is likely due to my lack of familiarity with the tool.

I would deeply appreciate any help, thanks. 

PS The `redis` component worked flawlessly. 

/kind bug

**Comment by LukasGentele** [comment]
Hi @jorge0136 ! Thanks for reporting this. I believe you are not using the newest version DevSpace v4.0.3 because otherwise, DevSpace would have written the component as helm chart deployment. So, I would recommend upgrading using: `devspace upgrade`

We changed that to make it more understandable how components work. So, you above config could also be written like this (which will be the default way of writing component deployments in the future):
```yaml
version: v1beta3
deployments:
- name: postgres-1
  helm:
    chart:
      name: component-chart
      version: v0.0.6
      repo: https://charts.devspace.cloud
    values:
        containers:
        - image: postgres:9.6
        env:
        - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
            value: mydev
        - name: POSTGRES_PASSWORD
            value: password
        volumeMounts:
        - containerPath: /var/lib/postgresql/data/pgdata
            volume:
            name: postgres-data
            subPath: /postgres
        volumes:
        - name: postgres-data
        size: 1Gi
        service:
        name: postgres
        ports:
        - port: 5432
dev: {}
```

Here you can now see that components are deployed with a helm chart which is made for very flexible deployments. It is much easier and better readable than plain manifests but allows pretty much the same flexibility. The templates and other source code of the chart can be found here but is rather complex and therefore, pretty hard to read: https://github.com/devspace-cloud/helm-charts/tree/master/component-chart

However, we stick pretty much to the regular k8s naming for all config options and all available options are documented here: https://devspace.cloud/docs/cli/deployment/components/configuration/overview-specification

Regarding your question about postgres: So, the config you pasted above simply deploys a statefulset with 1 container using the `postgres:9.6` image. The docs for this image are here: https://hub.docker.com/_/postgres

The problem you are experiencing I believe is that the image unfortunately only sets the username and password the very first time the container is being started and the pg-data directory `/var/lib/postgresql/data/pgdata` is still empty. Any changes to the env vars will not be considered after the image has been started once and has populated the database into the data directory. 

When I run this, everything works as expected:
1. `devspace add deployment --component=postgres database`
2. `devspace deploy` 
3. `devspace enter` => choosing the main dev container, not postgres
4. inside the container `psql -h postgres -p 5432 -U mydev`

So, I am not sure why the username and password were not applied during the very first deployment, but it makes sense that it will not work for any following deployment. You could fix this issue by doing the following:
1. `devspace purge -s`
2. `kubectl get pv` => see if there is still a persistent volume for your postgres and delete it using `kubectl delete pv [pv-name]`
3. `devspace deploy -s`

=> If there is no old persistent volume and you redeploy everything, the postgres container should initialize the database again and this time it should use the env vars to set username and password when starting the container for the very first time.

Let me know if that fixes the issue or if there is still something open for us to look into.
