### ISSUE TITLE
Unable to create persistent volume using YAML file

### ISSUE THREAD

**Issue by slevine111** [devspace-cloud/devspace#749]
**What happened?**  
I'm unable to create a persistent volume using yaml file and kubectl deploy option. Below is my YAML file
```
apiVersion: v1  
  kind: PersistentVolume
metadata:
  name: postgresql-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: '/mnt/data/postgresql'
```

I then get the following error
```
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "/v1, Resource=persistentvolumes", GroupVersionKind: "/v1, Kind=PersistentVolume"
Name: "postgresql-pv-volume", Namespace: ""
Object: &{map["apiVersion":"v1" "kind":"PersistentVolume" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "name":"postgresql-pv-volume"] "spec":map["accessModes":["ReadWriteOnce"] "capacity":map["storage":"2Gi"] "hostPath":map["path":"/mnt/data/postgresql"] "persistentVolumeReclaimPolicy":"Retain" "storageClassName":"manual" "volumeMode":"Filesystem"]]}
from server for: "STDIN": persistentvolumes "postgresql-pv-volume" is forbidden: User "system:serviceaccount:worldofchatting-d3646568:devspace" cannot get resource "persistentvolumes" in API group "" at the cluster scope
```

**What did you expect to happen instead?**  
Persistent volume created

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. clone my repo ```https://github.com/slevine111/WorldOfChatting```
2. checkout the develop branch
3. create a space on devspace
4. run devspace deploy on the develop branch

**Local Environment:**  
- Operating System: mac
- Deployment method: kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: DevSpace Cloud 
- Kubernetes Version: 
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.9-gke.15"}

**Anything else we need to know?**  
Here is my ~/.kube/config-devspace
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ***
    server: ***
  name: devspace-my-app
contexts:
- context:
    cluster: devspace-my-app
    namespace: my-app-0167643e
    user: devspace-my-app
  name: devspace-my-app
current-context: devspace-my-app
kind: Config
preferences: {}
users:
- name: devspace-my-app
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - use
      - space
      - --provider
      - app.devspace.cloud
      - --space-id
      - "681"
      - --get-token
      command: devspace
      env: null
```
Here is my ~/.kube/config
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ***
    server: ***
  name: devspace-worldofchatting
- cluster:
    certificate-authority: ***
    server: ***
  name: minikube
contexts:
- context:
    cluster: devspace-worldofchatting
    namespace: worldofchatting-d3646568
    user:  devspace-worldofchatting
  name: devspace-worldofchatting
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: devspace-worldofchatting
kind: Config
preferences: {}
users:
- name: devspace-worldofchatting
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - use
      - space
      - --provider
      - app.devspace.cloud
      - --space-id
      - "932"
      - --get-token
      - --silent
      command: devspace
      env: null
- name: minikube
  user:
    client-certificate: **
    client-key: ***
```

/kind bug

**Comment by LukasGentele** [comment]
Hi @slevine111! Creating persistent volumes directly is not permitted in DevSpace Cloud managed clusters. Instead, you will have to create a persistent volume claim and then a persistent volume will be created for this claim: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims

The reason why it is not allowed to create persistent volumes directly is that they are not namespaced, instead they are cluster-wide resources. In DevSpace Cloud you can only create resources in your namespace and nothing which cluster-wide, so you have to create a persistent volume claim in your namespace/space and then the cluster will create the persistent volume for you.

In your case, you want to create a postgres database. Instead of creating the yaml files yourself, you could simply tell DevSpace to use the postgresql helm chart. You can do this by adding this to the `deployments` section, so that your `devspace.yaml` would look like this:
```yaml
version: v1beta3
images:
  webserver:
    image: dscr.io/slevine111/worldofchatting
    createPullSecret: true
deployments:
  - name: database
    helm:
      chart:
        name: stable/postgresql
      values:
        postgresqlDatabase: "db_website"
        postgresqlUsername: "db_user"
        postgresqlPassword: ${DB_PASSWORD}
  - name: worldofchatting
    kubectl:
      manifests:
        - k8s
dev:
  sync:
    - imageName: default
      excludePaths:
        - node_modules
        - npm-debug.log
        - .git
        - .gitignore
        - Dockerfile
        - k8s
        - devspace.yaml/
```

After adding this, just run `devspace dev` or `devspace deploy` and DevSpace will ask you to provide a value for `${DB_PASSWORD}` and then create the postgres database for you. You can connect to the database via hostname: `database-postgresql`

Hope that helps. Let me know if anything is unclear.

**Comment by LukasGentele** [comment]
@slevine111 Were you able to provision your persistent volumes with my explanation above or are there still questions open regarding this issue? Let me know if we can close this.

**Comment by slevine111** [comment]
@LukasGentele Sorry for delayed response. Yep I was able to provision the persistent volume. Thanks a lot for your detailed explanation. I sticked to using manifests. i haven't yet read up on Helm but I plan to and give that a go.

I'm now having some trouble with devspace in CircleCI. Specifically I'm having trouble when I try to run "devspace use space worldofhchatting." worldofchatting is the space I have previously created. Below are my config.yml file for DircleCI and screenshots of the installation of devspace and devspace login in CircleCI running successfully and then the error I'm getting with devspace use space. Would you like me to create a separate issue for this? Thanks

<img width="1169" alt="SuccessfulDevspaceSteps" src="https://user-images.githubusercontent.com/24880825/67624145-16083780-f7fb-11e9-918c-96d420e302ea.png">

<img width="1166" alt="DevspaceusespaceError" src="https://user-images.githubusercontent.com/24880825/67624150-1acceb80-f7fb-11e9-85eb-34b802db050b.png">

```
version: 2
jobs:
  build_and_deploy:
    docker:
      # specify the version you desire here
      - image: circleci/buildpack-deps:jessie

    steps:
      - checkout

      - run:
          name: put environment variables in secrets
          command: |
            POSTGRES_USER_ENCODED=$(echo $POSTGRES_USER | base64)
            POSTGRES_PASSWORD_ENCODED=$(echo $POSTGRES_PASSWORD | base64)
            REDIS_PASSWORD_ENCODED=$(echo $REDIS_PASSWORD | base64)
            JWT_SECRET_ENCODED=$(echo $JWT_SECRET | base64)
            jwt_secret_lines=$(echo $JWT_SECRET_ENCODED | tr " " "\n")
            sed -i "s/ENV-VAR-POSTGRES-USER/${POSTGRES_USER_ENCODED}/" ./k8s/secret.yaml
            sed -i "s/ENV-VAR-POSTGRES-PASSWORD/${POSTGRES_PASSWORD_ENCODED}/" ./k8s/secret.yaml
            sed -i "s/ENV-VAR-REDIS-PASSWORD/${REDIS_PASSWORD_ENCODED}/" ./k8s/secret.yaml
            for line in $jwt_secret_lines
            do
                sed -i "s/ENV-VAR-JWT-SECRET/${line}ENV-VAR-JWT-SECRET/" ./k8s/secret.yaml
            done
            sed -i "s/ENV-VAR-JWT-SECRET//" ./k8s/secret.yaml

      - run:
          name: install devspace
          command: |
            curl -s -L "https://github.com/devspace-cloud/devspace/releases/latest" |\
            sed -nE 's!.*"([^"]*devspace-linux-amd64)".*!https://github.com\1!p' | xargs -n 1 curl -L -o devspace && chmod +x devspace;
            sudo mv devspace /usr/local/bin;

      - run:
          name: devspace login
          command: devspace login --key ${DEVSPACE_CLOUD_ACCESS_KEY}

      - run:
          name: set up space to use
          command: devspace use space worldofchatting

      - run:
          name: deploy
          command: devspace deploy

  test:
    docker:
      # specify the version you desire here
      - image: circleci/buildpack-deps:jessie

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: build test image
          command: docker-compose build

      - run:
          name: test
          command: docker-compose run webserver npm run test

      - run:
          name: containers
          command: |
            docker container ls
            docker container ls -a

      - run:
          name: copy coverage file
          command: docker cp worldofchatting-webserver-test:/user/src/app/coverage-circleci ./coverage-circleci

      - run:
          name: check
          command: |
            pwd
            ls

      - store_artifacts:
          path: ./coverage-circleci

workflows:
  version: 2
  test_build_and_deploy:
    jobs:
      - test
      - build_and_deploy:
          requires:
            - test
          filters:
            branches:
              ignore: master
```
