### ISSUE TITLE
Unable to enable auto-scaling

### ISSUE THREAD

**Issue by kienct89** [devspace-cloud/devspace#789]
**What happened?**  

unable to use auto-scaling feature

**What did you expect to happen instead?**  

auto-scaling should be enabled

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Follow the guide in (https://devspace.cloud/docs/cli/deployment/components/configuration/scaling#configure-horizontal-auto-scaling)

Sample yaml

```
deployments:
- name: testservice
  helm:
    componentChart: true
    values:
      replicas: 2
      autoScaling:
        horizontal:
          maxReplicas: 10
          averageCPU: 800m
      containers:
      - image: 
      service:
        ports:
        - port: 80
      rollingUpdate:
        enabled: true
        maxUnavailable: "50%"
```

**Local Environment:**  
- Operating System: windows
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: azure
- Kubernetes Version: 1.14.8

**Anything else we need to know?**  

Error message:

`Unable to deploy helm chart: helm upgrade: rpc error: code = Unknown desc = render error in "component-chart/templates/pod-autoscaling.yaml": template: component-chart/templates/pod-autoscaling.yaml:24:14: executing "component-chart/templates/pod-autoscaling.yaml" at <$.Release.Name.name>: can't evaluate field name in type interface {}`

/kind bug
