### ISSUE TITLE
Unmarshal error of args field in custom builder

### ISSUE THREAD

**Issue by vinzenzs** [devspace-cloud/devspace#830]
According to the documentation for custom builders the field args should be used but pkg/devspace/config/versions/v1beta4/schema.go on line 87 states Args []*string `yaml:"flags,omitempty"` that the name is flags.

**What happened?**  
```
devspace build
[fatal]  convert config: Error loading config: yaml: unmarshal errors:
  line 17: field args not found in type v1beta4.CustomConfig
 ```
**How can we reproduce the bug?** 
Create a config file with the args argument
```
version: v1beta4
images:
  default:
    image: registry/dev
    build:
      custom:
        command: ./custom/build
        imageFlag: image
        args: []
        onChange: []
```
**Local Environment:**  
- Operating System:  mac

/kind bug
