### ISSUE TITLE
Remote manifests (https) in kubectl deployments not working

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#864]
**Is your feature request related to a problem?**  

Developing locally using Docker for Mac kubernetes, I have manually installed NGINX Ingress Controller. For use by other developers without setup prerequisites, I wanted to put this into a deployment added via a patch in the dev profile:
```yaml
      name: nginx-ingress-controller
      kubectl:
        manifests:
        # controller definitions
        - https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.27.0/deploy/static/mandatory.yaml
        # controller service (docker-for-mac specific!)
        - https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.27.0/deploy/static/provider/cloud-generic.yaml
```

However, this doesn't work for me.

**Which solution do you suggest?**  

Enable installation of remote manifests. I would expect that there are many use cases where external infrastructure is needed by a project, and there are not always helm charts available.

**Which alternative solutions exist?**  

Keep local copy of manifest. In the future kustomize could be used, but issue has been open for a long time:
https://github.com/kubernetes-sigs/kustomize/issues/970

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
@shaunc thanks for opening this issue! This is actually a bug, since we are only using `kubectl` for this under the hood and `kubectl` is supporting this.

**Comment by shaunc** [comment]
Great -- It seems you are doing a hash check, perhaps in order to possibly skip kubectl call. Presumably just not doing this check for remote manifests would be fine. Extra credit for actually caching hash of remote manifest to tell if there was a change. :)

**Comment by FabianKramm** [comment]
@shaunc yes the hashing is the problem, however currently the caching check for kubectl manifests is only used in rare cases, because figuring out if something was deployed already before is not an easy task for all resources and can lead to unintentional skipping (namespace was deleted and recreated for example). Caching for helm charts works much better imho.

**Comment by fg91** [comment]
I am using `devspace version 5.1.2` and applying remote manifests is not working.

```yaml
deployments:
- name: cuda_drivers
  kubectl:
    manifests:
    - https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/master/nvidia-driver-installer/cos/daemonset-preloaded.yaml
```
A bare `kubectl apply -f https://...` works.

Should this be working with this version @FabianKramm ?
Thank you

**Comment by FabianKramm** [comment]
@fg91 I think the problem here is that the manifest needs to be deployed to the kube-system namespace. It works for me like this:
```yaml
deployments:
- name: cuda_drivers
  namespace: kube-system
  kubectl:
    manifests:
    - https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/master/nvidia-driver-installer/cos/daemonset-preloaded.yaml
```

**Comment by fg91** [comment]
@FabianKramm thanks for your quick reply!
I had tried `devspace deploy --deployments=cuda_driver --namespace kube-system` beforehand but neither this, nor what you suggested works.
The command does not fail but when running `kubectl get ds --namespace kube-system` you can see that the DaemonSet `nvidia-driver-installer` which is supposed to be created does not appear.

**Comment by FabianKramm** [comment]
It works for me with just `devspace deploy -n any-namespace` and the config that I mentioned before:
```
version: v1beta9
deployments:
- name: cuda_drivers
  namespace: kube-system
  kubectl:
    manifests:
    - https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/master/nvidia-driver-installer/cos/daemonset-preloaded.yaml
```

and `devspace deploy -n kube-system`

```
devspace deploy -n kube-system --no-warn
[info]   Using kube context 'docker-desktop'
[info]   Using namespace 'kube-system'
daemonset.apps/nvidia-driver-installer created     
[done] √ Successfully deployed cuda_drivers with kubectl
[done] √ Successfully deployed!
         
Run: 
- `devspace open` to create an ingress for the app and open it in the browser 
- `devspace enter` to open a shell into the container 
- `devspace logs` to show the container logs
- `devspace analyze` to analyze the space for potential issues

$ kubectl get ds -n kube-system
NAME                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
kube-proxy                1         1         1       1            1           beta.kubernetes.io/os=linux   4d4h
nvidia-driver-installer   0         0         0       0            0           <none>                        4s
```
