### ISSUE TITLE
Feature request: ability to specify service name with helm deployments

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#865]
**Is your feature request related to a problem?**  

I created a dummy service in my dev protocol:

```
  - op: add
    path: deployments[0]
    value:
      name: wisdom
      helm:
        chart:
          repo: https://kubernetes-charts-incubator.storage.googleapis.com
          name: webpagetest-server
        values:
          serviceType: NodePort
```

The name of the service is generated as `wisdom-webpagetest-server`. This is not optimal,
because I want to refer to this in a kubectl manifest across profiles, and the "webpagetest-server" part will change in other profiles. I want the service name to simply be "wisdom".

**Which solution do you suggest?**  

Either the name of the service should simply be the name of the deployment (in which case this is actually a bug report), or if the current behavior is deemed good for some reason, then a separate "name" or "serviceName" parameter should be added as configuration under "helm". The name of the chart in any case is no longer used as a default in helm 3.

**Which alternative solutions exist?**  

One could attempt to monkey patch the service name somehow.

**Additional context**  

/kind feature
