### ISSUE TITLE
devspace sync failed use of closed network connection

### ISSUE THREAD

**Issue by xiujuan95** [devspace-cloud/devspace#882]
**What happened?**  
I want to use `devspace sync` command to copy local files into a pod. I configure my pod like this:
```
apiVersion: v1
kind: Pod
metadata:
  name: copy-file
spec:
  containers:
  - name: copy-file
    image: k8s.gcr.io/busybox
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 100000"
```
And then use below command to copy files:
`devspace sync --pod copy-file --local-path=/path/to/localFiles --no-watch`
But it failed. It showed me the below error:
```
[wait] ⠋ Starting sync... (4s)E0117 15:56:01.244815   92062 v2.go:105] write tcp 9.181.91.2:54035->169.62.166.98:28450: use of closed network connection
[wait] ⠙ Starting sync... (553s)
```
I don't know if my steps to run this command is wrong or not? if it's wrong, how should I do about copying a folder into a pod. This pod has been configure in advance. 
Anybody has any idea? Thanks a lot!

**What did you expect to happen instead?**  

Copy files into a pod successfully
**How can we reproduce the bug?** (as minimally and precisely as possible)  

**Local Environment:**  
- Operating System: windows | linux | mac
mac
- Deployment method: helm | kubectl apply
kubectl apply
**Kubernetes Cluster:**  
- Cloud Provider: google | aws | azure | DevSpace Cloud | DevSpace Cloud Enterprise | other
- Kubernetes Version: [use `kubectl version`]

**Anything else we need to know?**  

/kind bug
