### ISSUE TITLE
Feature request: add "ssh" config (and build secrets) to docker image build options

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#884]
**Is your feature request related to a problem?**  

I would like to use an ssh key to access a private repo during image building. Building independently, I can pass via:
```
docker build --ssh projecta=./projecta.pem --ssh projectb=./projectb.pem -t ... .
```
[from https://medium.com/@tonistiigi/build-secrets-and-ssh-forwarding-in-docker-18-09-ae8161d066](https://medium.com/@tonistiigi/build-secrets-and-ssh-forwarding-in-docker-18-09-ae8161d066)

Multistage builds allow mounting of key from docker build context, but this is still suboptimal, especially in dependencies, as the dependency is taken straight from a repo, where it can't have the key in the build context (without security hole).

**Which solution do you suggest?**  

```yaml
build:
  docker:
    options:
      ssh:
        key1: path1
        key2: path2
```
would generate docker arguments, and also trigger `DOCKER_BUILDKIT=1` in build environment.

The same could be done with build secrets (though I don't need right now, if I have ssh):

```yaml
build:
  docker:
    options:
      secrets:
        key1: path1
        key2: path2
```
**Which alternative solutions exist?**  

If there is an alternative people are already using, would be pleased to know.

**Additional context**  

/kind feature
