### ISSUE TITLE
dependencies profile is wrong indentation in document

### ISSUE THREAD

**Issue by wickedev** [devspace-cloud/devspace#898]
**What happened?**  

dependencies profile is wrong indentation in document
https://devspace.cloud/docs/cli/deployment/advanced/dependencies

https://github.com/devspace-cloud/devspace/blob/master/pkg/devspace/config/versions/latest/schema.go

**What did you expect to happen instead?**  
should change as follows:

```yaml
dependencies:
  - source:
      git: https://github.com/my-auth-server
      revision: c967392
    profile: production
```

**How can we reproduce the bug?** (as minimally and precisely as possible)  

**Local Environment:**  
- Operating System: windows | linux | mac
- Deployment method: helm | kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: google | aws | azure | DevSpace Cloud | DevSpace Cloud Enterprise | other
- Kubernetes Version: [use `kubectl version`]

**Anything else we need to know?**  

/kind bug
