### ISSUE TITLE
"serviceName" parameter in ingress specification not respected

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#900]
**What happened?**  

I am creating an ingress as follows:
```
- name: nginx-s3-ingress
  helm:
    componentChart: true
    values:
      ingress:
        rules:
        - host: ${INGRESS_HOST}
          path: /wisdom
          serviceName: nginx-s3
          servicePort: 80
        annotations:
          kubernetes.io/ingress.class: "nginx"
          # NB: nginx-ingress appends $1 to pattern
          nginx.ingress.kubernetes.io/rewrite-target: "/"
```
However, the generated ingress looks as follows (abridged):
```
kind: Ingress
metadata:
  annotations:
    helm.sh/chart: component-chart-v0.0.8
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx-s3-ingress
  name: nginx-s3-ingress
  namespace: crane-web
spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          serviceName: nginx-s3-ingress
          servicePort: 80
        path: /wisdom
```

**What did you expect to happen instead?**  

Note that the deployed ingress has `serviceName: nginx-s3-ingress`, but the spec calls for `serviceName: nginx-s3`.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

The above snippet should give you a way to reproduce.

**Local Environment:**  
- Operating System: windows | linux | mac
- Deployment method: helm | kubectl apply

mac / helm

**Kubernetes Cluster:**  
- Cloud Provider: google | aws | azure | DevSpace Cloud | DevSpace Cloud Enterprise | other
- Kubernetes Version: [use `kubectl version`]

docker for Mac, 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@shaunc thanks for reporting! @LukasGentele will fix this as soon as possible!

**Comment by LukasGentele** [comment]
This is fixed via: https://github.com/devspace-sh/component-chart/releases/tag/v0.1.1

Should be shipped with the next DevSpace release. If you don't want to wait, you can also replace `componentChart: true` with:
```yaml
  chart:
    name: component-chart
    version: v0.1.1
    repo: https://charts.devspace.sh
```
That will get you the newest version of the chart. However, using the `componentChart: true` option is recommended because DevSpace will validate the values as part of the config and it will allow for automatic config upgrades.
