### ISSUE TITLE
patch vars fails

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#904]
**What happened?**  

I would like to set a variable value depending on profile. However, patching fails; for example, the configuration:
```
version: v1beta6
vars:
- name: foo
  source: env
  default: bar

profiles:
- name: test
  patches:
  - op: replace
    path: vars[0].default
    value: baz
```
Produces:
```
% devspace use profile test
[info]   Successfully switched to profile 'test'
% devspace print           
[fatal]  apply patches: yamlpatch replace operation does not apply: doc is missing path: /vars/0/default
```

**What did you expect to happen instead?**  

For the configuration to be printed, displaying the variable 'foo' set to value 'baz' at the top.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

The configuration above should be sufficient.

**Local Environment:**  
- Operating System: mac
- Deployment method: n.a.

**Kubernetes Cluster:**  
- Cloud Provider: n.a.
- Kubernetes Version: n.a.

**Anything else we need to know?**  

I assume variables are stripped out earlier in process. If it is hard to support patching variables, it should be documented. To support per-profile variable values, a `vars` section could be added to profiles -- such that variables in the profile configuration override those in the main configuration if they have the same names.

/kind bug
