### ISSUE TITLE
Ingress w/ tls creation triggers erroneous certificate creation

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#913]
**What happened?**  

When creating an ingress with `cert-manager.io/cluster-issuer: "letsencrypt-dev"` annotation, a Certificate is added to the manifest, which then gives the error on deploy:
```
Error deploying crane-wisdom: Unable to deploy helm chart: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Certificate" in version "certmanager.k8s.io/v1alpha1"
```

The config is:
```
version: v1beta6
deployments:
- name: foo
  helm:
    # TODO: revert on next devspace release
    # componentChart: true
    chart:
      name: component-chart
      version: v0.1.1
      repo: https://charts.devspace.sh
    values:
      ingress:
        rules:
        - host: foo.bar
          path: '/wisdom/api/(.*)'
          serviceName: nginx-s3
          servicePort: 80
          tls: "crane-wisdom-tls"
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-dev"
          nginx.ingress.kubernetes.io/rewrite-target: "/$1"
```
The output of `devspace render`:
```
---
# Source: component-chart/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "foo"
  labels:
    "app.kubernetes.io/name": "foo"
    "app.kubernetes.io/managed-by": "Helm"
  annotations:
    "helm.sh/chart": "component-chart-v0.1.1"
    "cert-manager.io/cluster-issuer": "letsencrypt-dev"
    "kubernetes.io/ingress.class": "nginx"
    "nginx.ingress.kubernetes.io/rewrite-target": "/$1"
spec:
  rules:
  - host: "foo.bar"
    http:
      paths:
      - backend:
          serviceName: "nginx-s3"
          servicePort: 80
        path: "/wisdom/api/(.*)"
  tls:
  - hosts:
    - foo.bar
    secretName: "crane-wisdom-tls"
---
# Source: component-chart/templates/ingress.yaml
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: "crane-wisdom-tls"
spec:
  acme:
    config:
    - domains:
      - foo.bar
      http01:
        ingressClass: "nginx"
  dnsNames:
  - foo.bar
  issuerRef:
    kind: ClusterIssuer
    name: "lets-encrypt-http-issuer"
  secretName: "crane-wisdom-tls"
```

**What did you expect to happen instead?**  

I am using cert-manager-v0.12.0 which requires `apiVersion: cert-manager.io/v1alpha2`. But beyond this, as far as I understand, the Certificate is created by cert-manager and shouldn't be created together with the ingress? (Also, I'm using DNS01/route53 ... but that config shouldn be on the ClusterIssuer? Perhaps because of different version of cert-manager.)

IMHO you are trying to be too clever here. Perhaps include a separate flag to generate a certificate, if it is necessary. (And then you need to maintain to correspond to cert-manager version. Hmm... is there an annotation for that that I can include in the ingress annotations? AFAIK this isn't necessary anymore even if it may have been once (?))

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Above configuration should suffice.

**Local Environment:**  
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: [use `kubectl version`]

**Anything else we need to know?**  

*Related issue*: `devspace render` doesn't add a carriage return after Certificate:
```
  secretName: "crane-wisdom-tls"---
```
(and then the next ingress when there are more than one...)

/kind bug

**Comment by shaunc** [comment]
NB this seems to happen only with the new chart. If I put `componentChart: true` back in and take out reference to the `0.1.1` chart, the Certificate records go away.

**Comment by LukasGentele** [comment]
Thanks for reporting this @shaunc. I took a closer look at this today. 

You are right. The issue is that we currently ship v0.10 of cert-manager in DevSpace Cloud (that's what I tested with) and you seem to use v0.11+ which requires the new extensions/v1beta1 CRD version. Generally, it is okay to create the certificate resource instead of using the annotations. I decided for this option because it allows more control (although not exposed yet via the charts values).

However, the problem with different CRD apiVersions is not solvable when creating the certificate directly. That's why we'll switch to annotations just like you suggested. I checked with the release notes and to provide compatibility for both v0.10 and v0.11+ we also need to set all annotations twice but with a different prefix but that should not be an issue during the deployment.

**Action required:** Using annotations does not allow to make differences on a host-basis regarding tls (but I think we can live with this). The annotation is for the entire ingress, hence there will only be `ingress.tls: bool|string` and `ingress.rules[].tls` will be removed / have no effect anymore.

I created a new version of the component chart v0.1.3 which will be shipped with the next DevSpace release. To test the new version now, use:
```
  chart:
    name: component-chart
    version: 0.1.3                               # note missing v prefix!
    repo: https://charts.devspace.sh
```
