### ISSUE TITLE
localSubPath is ignored by devspace sync

### ISSUE THREAD

**Issue by igoooor** [devspace-cloud/devspace#933]
**What happened?**  
First of all, it all works correctly when running `devspace dev`
But if I run it with `devspace dev --exit-after-deploy`, and then run `devspace sync --config=devspace.yaml`, the sync does not work properly.
Here is the sync defined in **devspace.yaml**:
```
dev:
  sync:
  - imageName: php
    localSubPath: ./docroot
    containerPath: /home/www-data/docroot
```

So when using `devspace dev`, the output of the sync is with the correct mapping of folders: 
`[done] √ Sync started on /.../my-project/docroot <-> /home/www-data/docroot`
But when using `devspace dev --exit-after-deploy`, and then run `devspace sync --config devspace.yaml` the output and mapping is:
`[done] √ Sync started on /.../my-project <-> /home/www-data/docroot`
We can see that the **localSubPath** is missing and it's using my current directory instead.
No matter what I type in the **localSubPath** it's ignored and using my current directory.
The **containerPath** is always correctly used though.

**Local Environment:**  
- Operating System: mac
- Deployment method: helm
- devspace version 4.5.0

**Kubernetes Cluster:**  
- Cloud Provider: local with docker for mac
- Kubernetes Version: 1.16

/kind bug

**Comment by FabianKramm** [comment]
@igoooor thanks for opening this issue! Yes you are correct, seems like the config localSubPath is not correctly applied when loading the sync config from file.

**Comment by evyros** [comment]
This issue exists on 5.14.3 on Apple Silicone.
It doesn't matter what value I give to `localSubPath` it's just being ignored.
```
version: v1beta10
images:
  api:
    image: org/api
deployments:
- name: rc
  helm:
    chart:
      name: ./k8s
    valuesFiles:
    - values.dev.yaml
dev:
  sync:
  - imageName: api
    labelSelector:
      tier: api
    containerName: api
    localSubPath: ./services/api
    excludePaths:
    - .git/

```
It is always using my current directory (project root, next to `devspace.yaml`).
Therefore I get this error:
```
[fatal]  error during shouldRebuild check: Dockerfile ./Dockerfile missing: stat ./Dockerfile: no such file or directory
```
