### ISSUE TITLE
vars asks question if source: env and not found

### ISSUE THREAD

**Issue by chasebolt** [devspace-cloud/devspace#950]
**What happened?**  
devspace keeps asking to define a var and does not use `default`.
```
? Please enter a value for DEVSPACE_APP_NAME
```

**What did you expect to happen instead?**  
If the var is not found in the env, then fallback to using `default` with no additional intervention.

**How can we reproduce the bug?** (as minimally and precisely as possible) 
Do not set an env for DEVSPACE_APP_NAME

```yaml
vars:
  - name: DEVSPACE_APP_NAME
    default: myapp
    source: env
```

**Local Environment:**  
- Operating System: linux
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: minikube
- Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

/kind bug

**Comment by FabianKramm** [comment]
@chasebolt thanks for opening this issue! This is working for me like it should with: 

```yaml
version: v1beta6
images:
  default:
    image: myimage/devspace
deployments:
- name: ${DEVSPACE_TEST}
  helm:
    componentChart: true
    values:
      containers:
      - image: myimage/devspace
      service:
        ports:
        - port: 3000
vars:
- name: DEVSPACE_TEST
  source: env
  default: fabian
```

No question is asked and devspace deploys the chart without asking with the value `fabian`. Could you provide a `devspace.yaml` which causes this issue?

**Comment by chasebolt** [comment]
it could be that `DEVSPACE_APP_NAME` is used in a dependency and not in the main `devspace.yaml`. try this out:

main/devspace.yaml
```yaml
version: v1beta6
images:
  default:
    image: myimage/devspace
vars:
- name: DEVSPACE_TEST
  source: env
  default: fabian
dependencies:
- source:
    path: ../dep
```
dep/devspace.yaml
```yaml
version: v1beta6
deployments:
- name: ${DEVSPACE_TEST}
  helm:
    componentChart: true
    values:
      containers:
      - image: myimage/devspace
      service:
        ports:
        - port: 3000
```

`devspace print` will output
```
Vars:
[info]   No vars found
```

and if you run `devspace dev` it will ask the question
```
$ devspace dev
[info]   Using kube context 'minikube'
[info]   Using namespace 'test'
[done] √ Created image pull secret test/devspace-auth-docker
[info]   Start resolving dependencies

? Please enter a value for DEVSPACE_TEST 
```
