### ISSUE TITLE
Cannot deploy bitnami helm chart

### ISSUE THREAD

**Issue by zadigus** [devspace-cloud/devspace#960]
**What happened?**  
I am working with the kubernetes cluster available through Docker for desktop under windows. I am using helm v2, as I am currently evaluating devspace and my current deployment tool is skaffold, which does not cope well with helm v3. Therefore, I performed the following actions:
```
helm init
helm repo add stable https://kubernetes-charts.storage.googleapis.com
helm repo add bitnami https://charts.bitnami.com/bitnami
```
Then, I created a special namespace for my deployments with devspace:
```
kubectl create namespace devspace
devspace use namespace devspace
```
After that, I wrote the following devspace configuration:
```
version: v1beta6
deployments:
- name: minio
  helm:
    componentChart: false
    chart:
      repo: https://charts.bitnami.com/bitnami
      name: minio
    values:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
        - name: assets.shopozor
          path: /
      mode: standalone
      clusterDomain: localhost
      persistence:
        enabled: false
        size: 10Gi
      disableWebUI: false
      accessKey:
        password: minio
      secretKey:
        password: minio123
      service:
        port: 9000
```
I tried to deploy it like this:
```
devspace dev
```
as well as 
```
devspace deploy
```
I get the following error:
```
[fatal]  Error deploying: Error deploying minio: Unable to deploy helm chart: failed to download "https://charts.bitnami.com/bitnami/minio-3.0.7.tgz" (hint: running `helm repo update` may help)
Run `devspace purge -d minio` and `devspace deploy` to recreate the chart
```
Performing a 
```
helm install -n minio bitnami/minio
```
works perfectly. Clicking the above provided link 

https://charts.bitnami.com/bitnami/minio-3.0.7.tgz

in my favorite browser successfully downloads the `tgz` archive. Running the corresponding skaffold configuration works perfectly too:
```
apiVersion: skaffold/v2alpha2
kind: Config
deploy:
  helm:
    releases:
      - name: minio
        chartPath: bitnami/minio
        remote: true
        namespace: dev
        overrides:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
            - name: assets.shopozor
              path: /
          mode: standalone
          clusterDomain: localhost
          persistence:
            enabled: false
            size: 10Gi
          disableWebUI: false
          accessKey:
            password: minio
          secretKey:
            password: minio123
          service:
            port: 9000
```

**What did you expect to happen instead?**  
I expected the helm chart to be successfully deployed.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
The steps are described in the above first section.

**Local Environment:**  
- DevSpace Version: 4.5.4
- Operating System: windows 
- Deployment method: helm v2

**Kubernetes Cluster:**  
- Cloud Provider: Docker for Desktop under Windows 10
- Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@zadigus thanks for reporting this issue! I suspect this is caused by the helm repo caching between versions (there are sometimes issues when using v2 and v3 together) and should be fixed by deleting the `~/.helm` folder, alternatively you can tell devspace to just use helm v2. The config you provided will use helm v3, so if you want to test devspace with helm v2 you can enable that via the v2 property in the deployments section. The above devspace config works for me without having to run any previous helm command.

**Comment by zadigus** [comment]
It works fine if I use
```
deployments:
- name: minio
  helm:
    v2: true
    [...]
```
Thanks for the hint.
