### ISSUE TITLE
ingress w/ tls secret doesn't render tls specification

### ISSUE THREAD

**Issue by shaunc** [devspace-cloud/devspace#976]
**What happened?**  

I am trying to create an ingress with a "tls" section by specifying `tls: secretName`. However, this doesn't work. For example, 
```yaml

version: v1beta6

deployments:
- name: x
  helm:
    componentChart: true
    values:
      containers:
      - image: factfiber/nginx-auth-jwt
      service:
        ports:
        - port: 80
      ingress:
        rules:
        - host: ${INGRESS_HOST}
          path: /wisdom
          servicePort: 80
          tls: "crane-web-tls"
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/issuer: "letsencrypt-dev-http"
          # auth via cookie in crane-jwt
          #   * check permissions include wisdom
          #   * include auth response headers for user_id and
          #     permissions
          nginx.ingress.kubernetes.io/auth-url: http://nginx-auth-jwt.crane-web.svc.cluster.local:8080/validate?claims_permissions=Money%20Fund%20Wisdom&responses_x-auth-user-id=user_id&responses_x-auth-permissions=permissions

          # force tls termination
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          # NB useful for EKS behind ELB: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#server-side-https-enforcement-through-redirect
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
```
Results in the following ingress specification:
```
$ devspace render
```
```yaml
# Source: component-chart/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "x"
  labels:
    "app.kubernetes.io/name": "x"
    "app.kubernetes.io/managed-by": "Helm"
  annotations:
    "helm.sh/chart": "component-chart-0.1.3"
    "cert-manager.io/cluster-issuer": "letsencrypt-dev-http"
    "kubernetes.io/ingress.class": "nginx"
    "nginx.ingress.kubernetes.io/auth-url": "http://nginx-auth-jwt.crane-web.svc.cluster.local:8080/validate?claims_permissions=Money%20Fund%20Wisdom&responses_x-auth-user-id=user_id&responses_x-auth-permissions=permissions"
    "nginx.ingress.kubernetes.io/force-ssl-redirect": "true"
    "nginx.ingress.kubernetes.io/ssl-passthrough": "false"
    "nginx.ingress.kubernetes.io/ssl-redirect": "true"
spec:
  rules:
  - host: "web.k8test.cranedata.com"
    http:
      paths:
      - backend:
          serviceName: "x"
          servicePort: 80
        path: "/wisdom"
```

**What did you expect to happen instead?**  

I expect, under `spec` there will be a tls section as follows:
```yaml
  tls:
  - hosts:
    - web.k8test.cranedata.com
    secretName: crane-web-tls
```

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Should be possible with above.

**Local Environment:**  
- DevSpace Version: 4.5.4
- Operating System: mac
- Deployment method: helm component chart

**Kubernetes Cluster:**  
- Cloud Provider: eks
- Kubernetes Version: [use `kubectl version`]
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  

/kind bug
