### ISSUE TITLE
patches.op.add functions unexpectedly

### ISSUE THREAD

**Issue by chasebolt** [devspace-cloud/devspace#994]
**Is your feature request related to a problem?**  
I am trying to add additional helm values but when doing so it wipes out previously set values

```yaml
      - op: add
        path: deployments[2].helm.values
        value:
          customSecretName: mysql
          backupSecretName: cloud-credentials
```

**Which solution do you suggest?**  
Allow the yaml patching for add to append instead of actually replace.

**Which alternative solutions exist?**  
@LukasGentele suggested using a `valuesFiles` coupled with `values`.

**Additional context**  

/kind feature
